#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo "Usage $0 <ensembleName> [caseDirectory] [additional_model_ensemble_args...]"
  echo "Examples:"
  echo "  $0 my_ensemble template_bas"
  echo "  $0 my_ensemble MISMIP_666 --pickup --skips 10"
  exit 1
fi

. scripts/common.sh

if [ ! -d venv ]; then
  if [ $( python3 --version 2>&1 | sed -r 's/^.+ 3\.([0-9]+)\..+$/\1/' ) -lt 7 ]; then
    echo "You need to be running python3 at least of version 3.7"
    exit 1
  fi

  echo "Setting up a python environment for model ensembler"
  python3 -m venv venv
  source venv/bin/activate

  pip install --upgrade pip setuptools
  pip install model_ensembler
else
  source venv/bin/activate
fi

CFG_DIR="`dirname $0`"
ENSEMBLE_TARGET="slurm"
ENSEMBLE_NAME="${1}"
ENSEMBLE_TEMPLATE_CASE="${2:-template}"

# All arguments after the first two are extra args for model_ensemble
shift 2
EXTRA_ARGS=("$@")

ENSEMBLE_CONFIG="cases/${ENSEMBLE_TEMPLATE_CASE}/ensemble/${ENSEMBLE_NAME}.yaml"
if [ "$ENSEMBLE_TYPE" == "local" ]; then
  ENSEMBLE_TARGET="dummy"
fi

sed -r \
  -e "s/NAME/${ENSEMBLE_NAME}/g" \
  -e "s/TEMPLATE/${ENSEMBLE_TEMPLATE_CASE}/g" \
  cases/$ENSEMBLE_TEMPLATE_CASE/ensemble/template.yaml \
  >${ENSEMBLE_CONFIG}

# Run model_ensemble with default parameters, config, target, and extra args at the end
echo "Running: model_ensemble -ms 30 -ct 30 -st 20 -rt 120 -p -v ${ENSEMBLE_CONFIG} $ENSEMBLE_TARGET ${EXTRA_ARGS[*]}"
model_ensemble -ms 30 -ct 30 -st 20 -rt 120 -p -v ${ENSEMBLE_CONFIG} $ENSEMBLE_TARGET "${EXTRA_ARGS[@]}"

exit $?
